Ocpp20 config impl
LastProject-ESIEE/OCPPConfigurationServer pull request #140
Opened 2024-02-23 11:23 UTC by tvelu77

The server is now capable of sending configurations and receiving response in OCPP 2.0

2024-02-23 15:57 UTC, Idhao commented on src/main/java/fr/uge/chargepointconfiguration/chargepointwebsocket/WebSocketMessage.java
>     * Defines the message type which the server could receive from the chargepoint.
better javadoc for this enum

2024-02-23 15:59 UTC, Idhao commented on src/main/java/fr/uge/chargepointconfiguration/chargepointwebsocket/WebSocketMessage.java
> +          array = message.substring(1, message.length() - 1).split(",", 3);
should deserve an technical explanation ex : why split 3 ?

2024-02-23 15:59 UTC, Idhao commented on src/main/java/fr/uge/chargepointconfiguration/chargepointwebsocket/ocpp/ocpp16/OcppConfigurationObserver16.java
> -      // TODO : Log, the chargepoint is ready !
todo should stay ?

2024-02-23 16:12 UTC, Idhao reviewed
waiting your modifs

2024-02-23 16:15 UTC, tvelu77 commented on src/main/java/fr/uge/chargepointconfiguration/chargepointwebsocket/WebSocketMessage.java
>     * Defines the message type which the server could receive from the chargepoint.
Done

[808e6e5](https://github.com/LastProject-ESIEE/OCPPConfigurationServer/pull/140/commits/808e6e51e4d32f2bb3e83b79ab830b933d6565ee)

2024-02-23 16:18 UTC, tvelu77 commented on src/main/java/fr/uge/chargepointconfiguration/chargepointwebsocket/WebSocketMessage.java
> +          array = message.substring(1, message.length() - 1).split(",", 3);
Done

[a2c471b](https://github.com/LastProject-ESIEE/OCPPConfigurationServer/pull/140/commits/a2c471b5e927284e9d02f4a1c97a2388d714406d)

2024-02-23 16:20 UTC, tvelu77 commented on src/main/java/fr/uge/chargepointconfiguration/chargepointwebsocket/ocpp/ocpp16/OcppConfigurationObserver16.java
> -      // TODO : Log, the chargepoint is ready !
Done

[ed79c97](https://github.com/LastProject-ESIEE/OCPPConfigurationServer/pull/140/commits/ed79c97bda9a45dee4d0c669dad6450f0dd575cc)

2024-02-23 17:36 UTC, Idhao commented on src/main/java/fr/uge/chargepointconfiguration/chargepointwebsocket/WebSocketMessage.java
>      return null;
null and nothing else ? are you okay ?

2024-02-23 17:38 UTC, Idhao requested changes
if the null part is volontary, then you can merge

2024-02-24 12:30 UTC, tvelu77 commented on src/main/java/fr/uge/chargepointconfiguration/chargepointwebsocket/WebSocketMessage.java
>      return null;
Totally normal, by default, we consider the message as a Response or something other than a request (it doesn't have a message type).
In the code, it is perfectly handled as it

2024-02-24 12:31 UTC, tvelu77 commented
@Idhao Requested an another review as the null part is volontary

2024-02-25 11:50 UTC, Idhao approved these changes
I understand now, ty incr doc

2024-02-25 12:10 UTC, merged